src/Entity/Countries.php
<?php

namespace App\Entity;

use App\Repository\CountriesRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CountriesRepository::class)]
class Countries
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $nb_inhabitants = null;

    #[ORM\Column(length: 255)]
    private ?string $capital_city = null;

    #[ORM\ManyToOne(inversedBy: 'countries')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Continents $continents = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getNbInhabitants(): ?int
    {
        return $this->nb_inhabitants;
    }

    public function setNbInhabitants(int $nb_inhabitants): self
    {
        $this->nb_inhabitants = $nb_inhabitants;

        return $this;
    }

    public function getCapitalCity(): ?string
    {
        return $this->capital_city;
    }

    public function setCapitalCity(string $capital_city): self
    {
        $this->capital_city = $capital_city;

        return $this;
    }

    public function getContinents(): ?Continents
    {
        return $this->continents;
    }

    public function setContinents(?Continents $continents): self
    {
        $this->continents = $continents;

        return $this;
    }
}

src/Form/CountriesType.php
<?php

namespace App\Form;

use App\Entity\Countries;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CountriesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('nb_inhabitants')
            ->add('capital_city')
            ->add('continents')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Countries::class,
        ]);
    }
}

src/Controller/CountriesController.php
<?php

namespace App\Controller;

use App\Entity\Countries;
use App\Form\CountriesType;
use App\Repository\CountriesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/countries')]
class CountriesController extends AbstractController
{
    #[Route('/', name: 'app_countries_index', methods: ['GET'])]
    public function index(CountriesRepository $countriesRepository): Response
    {
        return $this->render('countries/index.html.twig', [
            'countries' => $countriesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_countries_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CountriesRepository $countriesRepository): Response
    {
        $country = new Countries();
        $form = $this->createForm(CountriesType::class, $country);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $countriesRepository->save($country, true);

            return $this->redirectToRoute('app_countries_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('countries/new.html.twig', [
            'country' => $country,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_countries_show', methods: ['GET'])]
    public function show(Countries $country): Response
    {
        return $this->render('countries/show.html.twig', [
            'country' => $country,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_countries_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Countries $country, CountriesRepository $countriesRepository): Response
    {
        $form = $this->createForm(CountriesType::class, $country);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $countriesRepository->save($country, true);

            return $this->redirectToRoute('app_countries_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('countries/edit.html.twig', [
            'country' => $country,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_countries_delete', methods: ['POST'])]
    public function delete(Request $request, Countries $country, CountriesRepository $countriesRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$country->getId(), $request->request->get('_token'))) {
            $countriesRepository->remove($country, true);
        }

        return $this->redirectToRoute('app_countries_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/countries/_delete_form.html.twig
<form method="post" action="{{ path('app_countries_delete', {'id': country.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ country.id) }}">
    <button class="btn">Delete</button>
</form>

templates/countries/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/countries/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Countries{% endblock %}

{% block body %}
    <h1>Edit Countries</h1>

    {{ include('countries/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_countries_index') }}">back to list</a>

    {{ include('countries/_delete_form.html.twig') }}
{% endblock %}

templates/countries/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Countries index{% endblock %}

{% block body %}
    <h1>Countries index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Nb_inhabitants</th>
                <th>Capital_city</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for country in countries %}
            <tr>
                <td>{{ country.id }}</td>
                <td>{{ country.name }}</td>
                <td>{{ country.nbInhabitants }}</td>
                <td>{{ country.capitalCity }}</td>
                <td>
                    <a href="{{ path('app_countries_show', {'id': country.id}) }}">show</a>
                    <a href="{{ path('app_countries_edit', {'id': country.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_countries_new') }}">Create new</a>
{% endblock %}

templates/countries/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Countries{% endblock %}

{% block body %}
    <h1>Create new Countries</h1>

    {{ include('countries/_form.html.twig') }}

    <a href="{{ path('app_countries_index') }}">back to list</a>
{% endblock %}

templates/countries/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Countries{% endblock %}

{% block body %}
    <h1>Countries</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ country.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ country.name }}</td>
            </tr>
            <tr>
                <th>Nb_inhabitants</th>
                <td>{{ country.nbInhabitants }}</td>
            </tr>
            <tr>
                <th>Capital_city</th>
                <td>{{ country.capitalCity }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_countries_index') }}">back to list</a>

    <a href="{{ path('app_countries_edit', {'id': country.id}) }}">edit</a>

    {{ include('countries/_delete_form.html.twig') }}
{% endblock %}